name: Daily Job Tracker

on:
  schedule:
    - cron: '0 8 * * *' # every day at 08:00 UTC
  workflow_dispatch:

jobs:
  track-applications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run job mail tracker
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py

      - name: Commit updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add job_applications.xlsx reports/
          git commit -m "📬 Daily job update"
          git push
